# Generated by Django 4.2.4 on 2023-09-16 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('isEnabled', models.BooleanField(default=True)),
                ('parentLocation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_parentLocation', to='location.locations')),
            ],
        ),
        migrations.CreateModel(
            name='Locations_Versions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('lastAction', models.CharField(max_length=10)),
                ('lastEditedUserSignature', models.CharField(default='', max_length=200)),
                ('lastEditedDate', models.DateField(auto_now_add=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.locations')),
                ('parentLocation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_parentLocation_versions', to='location.locations')),
            ],
        ),
    ]
