# Generated by Django 3.2.20 on 2023-08-17 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='displayName',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='hierarchyNumber',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='parentLocationId',
        ),
        migrations.RemoveField(
            model_name='locations_versions',
            name='displayName',
        ),
        migrations.RemoveField(
            model_name='locations_versions',
            name='hierarchyNumber',
        ),
        migrations.RemoveField(
            model_name='locations_versions',
            name='parentLocationId',
        ),
        migrations.AddField(
            model_name='locations',
            name='parentLocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_parentLocation', to='location.locations'),
        ),
        migrations.AddField(
            model_name='locations_versions',
            name='parentLocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_parentLocation_versions', to='location.locations'),
        ),
    ]
