# Generated by Django 4.2.4 on 2023-09-16 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itemcategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('minimumStock', models.IntegerField()),
                ('isEnabled', models.BooleanField(default=True)),
                ('itemCategoryId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemcategory.itemcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Items_Versions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('minimumStock', models.IntegerField()),
                ('lastAction', models.CharField(max_length=10)),
                ('lastEditedUserSignature', models.CharField(default='', max_length=200)),
                ('lastEditedDate', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.items')),
                ('itemCategoryId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemcategory.itemcategory')),
            ],
        ),
    ]
