# Generated by Django 3.2.20 on 2023-09-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_isenabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='isEnabled',
            field=models.BooleanField(default=True),
        ),
    ]
