# Generated by Django 3.2.20 on 2023-09-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='linkedReports',
            field=models.ManyToManyField(related_name='_reports_reports_linkedReports_+', to='reports.Reports'),
        ),
    ]
