# Generated by Django 3.2.20 on 2023-09-18 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_alter_reports_linkedreports'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ReportReviewers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewDecision', models.CharField(max_length=10)),
                ('reviewed', models.BooleanField()),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reports',
            name='reportReviewers',
            field=models.ManyToManyField(related_name='reviewers', to='reports.ReportReviewers'),
        ),
    ]
