# Generated by Django 3.2.20 on 2023-09-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20230918_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportreviewers',
            name='reviewDecision',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='reportreviewers',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
