# Generated by Django 3.2.20 on 2023-09-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20230918_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='requiresReviewing',
            field=models.BooleanField(default=False),
        ),
    ]
