# Generated by Django 3.2.20 on 2023-09-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_reports_requiresreviewing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='requiresReviewing',
        ),
        migrations.AddField(
            model_name='reportreviewers',
            name='reviewerSignature',
            field=models.CharField(default='', max_length=200),
        ),
    ]
