# Generated by Django 3.2.20 on 2023-09-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20230918_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportreviewers',
            name='reviewerSignature',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
