# Generated by Django 3.2.20 on 2023-09-18 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_reportreviewers_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportreviewers_versions',
            name='reportReviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reportreviewers'),
        ),
    ]
