# Generated by Django 4.2.4 on 2023-09-16 20:24

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('documentBody', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('isEnabled', models.BooleanField(default=True)),
                ('ownerSignature', models.CharField(default='', max_length=200)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SOPAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d')),
                ('SOP', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='standardoperatingprotocols.sop')),
            ],
        ),
        migrations.CreateModel(
            name='SOPAttachments_Versions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=200)),
                ('lastAction', models.CharField(max_length=10)),
                ('lastEditedUserSignature', models.CharField(default='', max_length=200)),
                ('lastEditedDate', models.DateField(auto_now_add=True)),
                ('SOP', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='standardoperatingprotocols.sop')),
                ('SOPAttachmentsId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='standardoperatingprotocols.sopattachments')),
            ],
        ),
        migrations.CreateModel(
            name='SOP_Versions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('documentBody', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('lastAction', models.CharField(max_length=10)),
                ('lastEditedUserSignature', models.CharField(default='', max_length=200)),
                ('lastEditedDate', models.DateField(auto_now_add=True)),
                ('SOP', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='standardoperatingprotocols.sop')),
            ],
        ),
    ]
