# Generated by Django 3.2.20 on 2023-09-19 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('standardoperatingprotocols', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sop',
            name='trainee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sop',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer', to=settings.AUTH_USER_MODEL),
        ),
    ]
