# Generated by Django 3.2.20 on 2023-09-19 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('standardoperatingprotocols', '0002_auto_20230919_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sopattachments',
            name='SOP',
        ),
        migrations.AddField(
            model_name='sop',
            name='linkedAttachment',
            field=models.ManyToManyField(related_name='linkedAttachment', to='standardoperatingprotocols.SOPAttachments'),
        ),
        migrations.AddField(
            model_name='sop_versions',
            name='linkedAttachment',
            field=models.ManyToManyField(related_name='linkedAttachment_versions', to='standardoperatingprotocols.SOPAttachments'),
        ),
        migrations.AddField(
            model_name='sop_versions',
            name='trainee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainee_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sop_versions',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SOPAttachments_Versions',
        ),
    ]
