# Generated by Django 3.2.20 on 2023-09-19 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('standardoperatingprotocols', '0003_auto_20230919_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sop',
            name='trainee',
        ),
        migrations.AddField(
            model_name='sop',
            name='trainee',
            field=models.ManyToManyField(null=True, related_name='trainee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='sop',
            name='trainer',
        ),
        migrations.AddField(
            model_name='sop',
            name='trainer',
            field=models.ManyToManyField(null=True, related_name='trainer', to=settings.AUTH_USER_MODEL),
        ),
    ]
