# Generated by Django 3.2.20 on 2023-09-19 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('standardoperatingprotocols', '0004_auto_20230919_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sop',
            name='trainee',
            field=models.ManyToManyField(related_name='trainee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sop',
            name='trainer',
            field=models.ManyToManyField(related_name='trainer', to=settings.AUTH_USER_MODEL),
        ),
    ]
