# Generated by Django 3.2.20 on 2023-10-07 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemcategory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemCategory_Versions',
            new_name='ItemCategoryVersions',
        ),
    ]
