# Generated by Django 4.2.4 on 2023-09-16 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internalId', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField()),
                ('hasInternalId', models.BooleanField()),
                ('file', models.FileField(blank=True, null=True, upload_to='samplesDocs/%Y/%m/%d')),
                ('isEnabled', models.BooleanField(default=True)),
                ('locationId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.locations')),
            ],
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('isEnabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SampleType_Versions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('lastAction', models.CharField(max_length=10)),
                ('lastEditedUserSignature', models.CharField(default='', max_length=200)),
                ('lastEditedDate', models.DateField(auto_now_add=True)),
                ('sampleType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.sampletype')),
            ],
        ),
        migrations.CreateModel(
            name='Sample_Versions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internalId', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField()),
                ('hasInternalId', models.BooleanField()),
                ('lastAction', models.CharField(max_length=10)),
                ('lastEditedUserSignature', models.CharField(default='', max_length=200)),
                ('lastEditedDate', models.DateField(auto_now_add=True)),
                ('locationId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.locations')),
                ('sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.sample')),
                ('sampleType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.sampletype')),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='sampleType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.sampletype'),
        ),
    ]
